--------------------------------------------------------
--  파일이 생성됨 - 화요일-4월-28-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATTACH_DAEJEON
--------------------------------------------------------

  CREATE TABLE "JAVA"."ATTACH_DAEJEON" 
   (	"ANO" NUMBER, 
	"UPLOADPATH" VARCHAR2(300 BYTE), 
	"FILENAME" VARCHAR2(300 BYTE), 
	"BNO" NUMBER, 
	"ATTACHER" VARCHAR2(50 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"FILETYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JAVA.ATTACH_DAEJEON
SET DEFINE OFF;
Insert into JAVA.ATTACH_DAEJEON (ANO,UPLOADPATH,FILENAME,BNO,ATTACHER,REGDATE,FILETYPE) values (1,'c:\deajeon\board\file','c115efc4ead24a7eb55fa50bf43bf257$$1.jpg',196,'qwe123',null,'jpg');
--------------------------------------------------------
--  DDL for Index ATTACH_DEAJEON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA"."ATTACH_DEAJEON_PK" ON "JAVA"."ATTACH_DAEJEON" ("ANO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATTACH_DAEJEON
--------------------------------------------------------

  ALTER TABLE "JAVA"."ATTACH_DAEJEON" ADD CONSTRAINT "ATTACH_DEAJEON_PK" PRIMARY KEY ("ANO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA"."ATTACH_DAEJEON" MODIFY ("ANO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATTACH_DAEJEON
--------------------------------------------------------

  ALTER TABLE "JAVA"."ATTACH_DAEJEON" ADD CONSTRAINT "ATTACH_DEAJEON_FK1" FOREIGN KEY ("ATTACHER")
	  REFERENCES "JAVA"."MEMBER_DAEJEON" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "JAVA"."ATTACH_DAEJEON" ADD CONSTRAINT "ATTACH_DEAJEON_FK2" FOREIGN KEY ("BNO")
	  REFERENCES "JAVA"."BOARD_DAEJEON" ("BNO") ON DELETE CASCADE ENABLE;
