--------------------------------------------------------
--  파일이 생성됨 - 화요일-4월-28-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER_DAEJEON
--------------------------------------------------------

  CREATE TABLE "JAVA"."MEMBER_DAEJEON" 
   (	"ID" VARCHAR2(50 BYTE), 
	"PWD" VARCHAR2(60 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(150 BYTE), 
	"PICTURE" VARCHAR2(150 BYTE), 
	"AUTHORITY" VARCHAR2(30 BYTE), 
	"ENABLED" NUMBER DEFAULT 1, 
	"REGDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JAVA.MEMBER_DAEJEON
SET DEFINE OFF;
Insert into JAVA.MEMBER_DAEJEON (ID,PWD,NAME,PHONE,EMAIL,ADDRESS,PICTURE,AUTHORITY,ENABLED,REGDATE) values ('qwe123','qwe123','강현지','01023452345','patiss12r@naver.com','대전 중구 선화로 108번길',null,null,1,to_date('20/04/28','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index MEMBER_DAEJEON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA"."MEMBER_DAEJEON_PK" ON "JAVA"."MEMBER_DAEJEON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_DAEJEON
--------------------------------------------------------

  ALTER TABLE "JAVA"."MEMBER_DAEJEON" ADD CONSTRAINT "MEMBER_DAEJEON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA"."MEMBER_DAEJEON" MODIFY ("ID" NOT NULL ENABLE);
