--------------------------------------------------------
--  파일이 생성됨 - 화요일-4월-28-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REPLY_DAEJEON
--------------------------------------------------------

  CREATE TABLE "JAVA"."REPLY_DAEJEON" 
   (	"RNO" NUMBER, 
	"BNO" NUMBER, 
	"REPLYTEXT" VARCHAR2(600 BYTE), 
	"REPLYER" VARCHAR2(50 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"UPDATEDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JAVA.REPLY_DAEJEON
SET DEFINE OFF;
Insert into JAVA.REPLY_DAEJEON (RNO,BNO,REPLYTEXT,REPLYER,REGDATE,UPDATEDATE) values (1,1,'replytest1','qwe123',to_date('20/04/28','RR/MM/DD'),to_date('20/04/28','RR/MM/DD'));
Insert into JAVA.REPLY_DAEJEON (RNO,BNO,REPLYTEXT,REPLYER,REGDATE,UPDATEDATE) values (2,1,'asdf','qwe123',to_date('20/04/28','RR/MM/DD'),to_date('20/04/28','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index REPLY_DEAJEON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA"."REPLY_DEAJEON_PK" ON "JAVA"."REPLY_DAEJEON" ("RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REPLY_DAEJEON
--------------------------------------------------------

  ALTER TABLE "JAVA"."REPLY_DAEJEON" ADD CONSTRAINT "REPLY_DEAJEON_PK" PRIMARY KEY ("RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA"."REPLY_DAEJEON" MODIFY ("RNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REPLY_DAEJEON
--------------------------------------------------------

  ALTER TABLE "JAVA"."REPLY_DAEJEON" ADD CONSTRAINT "REPLY_DEAJEON_FK1" FOREIGN KEY ("BNO")
	  REFERENCES "JAVA"."BOARD_DAEJEON" ("BNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "JAVA"."REPLY_DAEJEON" ADD CONSTRAINT "REPLY_DEAJEON_FK2" FOREIGN KEY ("REPLYER")
	  REFERENCES "JAVA"."MEMBER_DAEJEON" ("ID") ON DELETE CASCADE ENABLE;
